export { default as Navbar } from './Navabr'
export { default as Hero } from './Hero'
export { default as Highlight } from './Highlights'
export { default as Model } from './Model'
export { default as Features } from './Features'
export { default as HowItWorks } from './HowItWorks'
export { default as Footer } from './Footer'
export { default as VideoCarousel } from './VideoCarousel'